// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AlquilaFacilPlatform.Tests.CoreBehaviourDrivenDevelopment
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ActualizarPerfilYSesionDeUsuarioFeature : object, Xunit.IClassFixture<ActualizarPerfilYSesionDeUsuarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US13ActualizarPerfilYSesiónDeUsuario.feature"
#line hidden
        
        public ActualizarPerfilYSesionDeUsuarioFeature(ActualizarPerfilYSesionDeUsuarioFeature.FixtureData fixtureData, AlquilaFacilPlatform_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CoreBehaviourDrivenDevelopment", "Actualizar perfil y sesión de usuario", "  Como usuario de AlquilaFácil,\r\n  Quiero poder modificar mi perfil, incluyendo l" +
                    "a opción de cambiar mi nombre de usuario y cerrar sesión,\r\n  Para mantener actua" +
                    "lizada mi información personal y gestionar mi acceso a la aplicación de manera c" +
                    "onveniente.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Modificación del nombre de usuario")]
        [Xunit.TraitAttribute("FeatureTitle", "Actualizar perfil y sesión de usuario")]
        [Xunit.TraitAttribute("Description", "Modificación del nombre de usuario")]
        [Xunit.InlineDataAttribute("JuanPérez", "JuanPérez123", new string[0])]
        [Xunit.InlineDataAttribute("MariaLopez", "MariaLopez456", new string[0])]
        [Xunit.InlineDataAttribute("CarlosGomez", "CarlosGomez789", new string[0])]
        public void ModificacionDelNombreDeUsuario(string nombreDeUsuario, string nuevoNombreDeUsuario, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Nombre de usuario", nombreDeUsuario);
            argumentsOfScenario.Add("nuevo nombre de usuario", nuevoNombreDeUsuario);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modificación del nombre de usuario", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("que el usuario ha iniciado sesión en su cuenta de AlquilaFácil", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.When(string.Format("accede a la sección de configuración de perfil y edita el campo \"{0}\"", nombreDeUsuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
    testRunner.Then(string.Format("puede guardar los cambios, y el {0} se refleja en su perfil y en todas las intera" +
                            "cciones futuras en la plataforma", nuevoNombreDeUsuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Cierre de sesión")]
        [Xunit.TraitAttribute("FeatureTitle", "Actualizar perfil y sesión de usuario")]
        [Xunit.TraitAttribute("Description", "Cierre de sesión")]
        [Xunit.InlineDataAttribute("JuanPérez", "cerrada", new string[0])]
        [Xunit.InlineDataAttribute("MariaLopez", "cerrada", new string[0])]
        [Xunit.InlineDataAttribute("CarlosGomez", "cerrada", new string[0])]
        public void CierreDeSesion(string usuario, string sesion, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("usuario", usuario);
            argumentsOfScenario.Add("sesión", sesion);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cierre de sesión", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
    testRunner.Given(string.Format("que el {0} desea salir de su cuenta en AlquilaFácil", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
    testRunner.When("selecciona la opción \"Cerrar sesión\" en la configuración de perfil", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
    testRunner.Then(string.Format("es desconectado de su cuenta y redirigido a la pantalla de inicio de sesión, aseg" +
                            "urando que su {0} se haya cerrado de manera segura", sesion), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ActualizarPerfilYSesionDeUsuarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ActualizarPerfilYSesionDeUsuarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
